language: node_js
node_js:
  - "stable"

jobs:
  include:
    - stage: test
      before_script: export NODE_OPTIONS=–max_old_space_size=4096
      script: jest --config jestconfig.json --coverage --coverageReporters=text-lcov | coveralls
